server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          # Keycloak
          issuer-uri: "http://localhost:8085/realms/master"

  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
          routes:
            - id: core-banking-service
              uri: http://localhost:8081
              predicates:
                - Path=/core-banking-service/**
              filters:
                - StripPrefix=1

            - id: advanced-features-service
              uri: http://localhost:8082
              predicates:
                - Path=/advanced-features-service/**
              filters:
                - StripPrefix=1






  # Rate limiter
#  cloud:
#    gateway:
#      routes:
#        - id: payment-service
#          uri: http://localhost:8083
#          predicates:
#            - Path=/api/payments/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

        #Health - Shows whether the application is running properly. (DEFAULT)
        #info - Shows application metadata.
        #prometheus - This exposes metrics in Prometheus format.

  endpoint:
    health:
      show-details: always
      #Show full health details to everyone not just status




springdoc:
  swagger-ui:
    urlsPrimaryName: core-banking-service
    urls:
      - name: core-banking-service
        url: /core-banking-service/v3/api-docs
      - name: advanced-features-service
        url: /advanced-features-service/v3/api-docs








