server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          # Keycloak
          issuer-uri: "http://localhost:8085/realms/master"

  data:
    redis:
      host: localhost
      port: 6379


  # Rate limiter
#  cloud:
#    gateway:
#      routes:
#        - id: payment-service
#          uri: http://localhost:8083
#          predicates:
#            - Path=/api/payments/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

        #Health - Shows whether the application is running properly. (DEFAULT)
        #info - Shows application metadata.
        #prometheus - This exposes metrics in Prometheus format.

  endpoint:
    health:
      show-details: always
      #Show full health details to everyone not just status
      #Sparsh Chaudhari





