name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build API Gateway
        run: |
          cd api-gateway
          mvn clean package -Dmaven.test.skip=true

      - name: Build Core Banking Service
        run: |
          cd core-banking-service
          mvn clean package -Dmaven.test.skip=true

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            echo "Going to project directory..."
            cd /home/ubuntu/FluxBank

            echo "Syncing repository..."
            git fetch origin
            git reset --hard origin/main
            git clean -fd

            echo "Stopping existing Java services (if running)..."
            pkill -f "api-gateway.jar" || true
            pkill -f "core-banking-service.jar" || true

            sleep 3

            echo "Building services on EC2..."

            cd api-gateway
            mvn clean package -Dmaven.test.skip=true

            cd ../core-banking-service
            mvn clean package -Dmaven.test.skip=true

            echo "Starting API Gateway..."
            cd ../api-gateway
            nohup java -jar target/*.jar > gateway.log 2>&1 &

            echo "Starting Core Banking Service..."
            cd ../core-banking-service
            nohup java -jar target/*.jar > core.log 2>&1 &

            echo "Deployment finished successfully!"
